[package]
name = "mmmproc"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.5", features = ["json"] } 
tokio = { version = "1", features = ["full"] }
rand = "0.8.5"
serde = "1.0.204"
serde_json = "1.0.120"

